######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 20 23:51:56 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
